### ISSUE TITLE
About the ablation study.

### ISSUE THREAD

**Issue by TiankaiHang** [zhoudaquan/Refiner_ViT#1]
Hi, thanks for your nice work!

I have one question, here you introduce linear projection W_A
![image](https://user-images.githubusercontent.com/52823230/121280080-40dbcc80-c908-11eb-92f3-d7732e89de6b.png)
The parameters of W_A (r * H * H) are related to the ratio. However, in your ablation study(table 1),
![image](https://user-images.githubusercontent.com/52823230/121280186-708ad480-c908-11eb-8296-83c69d065b8c.png)
That confuses me... Can i ask why?

**Comment by zhoudaquan** [comment]
> Hi, thanks for your nice work!
> 
> I have one question, here you introduce linear projection W_A
> ![image](https://user-images.githubusercontent.com/52823230/121280080-40dbcc80-c908-11eb-92f3-d7732e89de6b.png)
> The parameters of W_A (r * H * H) are related to the ratio. However, in your ablation study(table 1),
> ![image](https://user-images.githubusercontent.com/52823230/121280186-708ad480-c908-11eb-8296-83c69d065b8c.png)
> That confuses me... Can i ask why?

Hi Tiankai,

Thanks for your interests in this work! For your question, the number of parameters included in the linear expansion/project layer is calculated as #Heads^2 * #Expansion. As we typically use 12 heads, the total number of parameter overheads with expansion ratio of 6 is 144 * 6. Thus, when combined with the total number of parameters in the model, there are actually negligible.  If we take two more decimal precision, they are reflected in a magnitude of less than 0.1M.

I hope this clarify your question. If you  need any other clarifications,  do drop me a message.

**Comment by TiankaiHang** [comment]
Thanks for your kind reply :-)
