### ISSUE TITLE
特征图可视化

### ISSUE THREAD

**Issue by cenchaojun** [zhoudaquan/Refiner_ViT#4]
您好，非常感谢你们杰出的贡献，不过我们想了解，关于Fig5的图像是如何可视化出来的，或者有什么实例，非常感谢

**Comment by zhoudaquan** [comment]
> 您好，非常感谢你们杰出的贡献，不过我们想了解，关于Fig5的图像是如何可视化出来的，或者有什么实例，非常感谢

您好， Refiner 的可视化代码和DeepViT是一样的， 请参考这个link里面的code。

https://drive.google.com/drive/folders/1_lxspG_nzPstxDWhKQqPWhYZlB6zPMGs?usp=sharing

**Comment by cenchaojun** [comment]
> > 您好，非常感谢你们杰出的贡献，不过我们想了解，关于Fig5的图像是如何可视化出来的，或者有什么实例，非常感谢
> 
> 您好， Refiner 的可视化代码和DeepViT是一样的， 请参考这个link里面的code。
> 
> https://drive.google.com/drive/folders/1_lxspG_nzPstxDWhKQqPWhYZlB6zPMGs?usp=sharing

非常感谢，我已经看到代码的提交了，谢谢您
